[package]
name = "paguro"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Paguro, a UCI chess engine"
authors = ["Sandro Corsini"]
readme = "README.md"
exclude = ["/target/**", "/secrets/**"]

[[bin]]
name = "paguro"
path = "src/main.rs"

[lib]
name = "paguro"
path = "src/lib.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.release.build-override]
opt-level = 3
